blockType: DIRT
pathDuration: 10
pluginTag: "&5[PathEffects]"
messages:
  path:
    usage: "&cKullanım: &b/patheffects start"
    path-started: "&aYol efektleri başladı!"
    path-ended: "&cYol efektleri bitti!"
    path-already-started: "&cYol efektleri zaten başladı!"
  no-permission: "&cBu komutu kullanmak için yetkiniz yok!"
  config-reloaded: "&aConfig dosyası yeniden yüklendi!"


