name: PathEffects
version: '${version}'
main: me.streetmelodeez.patheffects.PathEffects
api-version: '1.20'
author: StreetMelodeez
commands:
  patheffects:
    description: "patheffects komutu"
    usage: /patheffects start
    permission: patheffects.admin